  // Copyright 2022 Elanskiy Alexandr

#ifndef MODULES_ELANSKI_ALEXANDR_EULER_FUNCTIONS_INCLUDE_EULER_FUNCTIONS_H_
#define MODULES_ELANSKI_ALEXANDR_EULER_FUNCTIONS_INCLUDE_EULER_FUNCTIONS_H_

#include <iostream>

class class_for_fun {
 public:
    int Function_Euler(int number);
};

#endif  // MODULES_ELANSKI_ALEXANDR_EULER_FUNCTIONS_INCLUDE_EULER_FUNCTIONS_H_
